ci:
  autofix_prs: true
  autoupdate_schedule: quarterly

repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: no-commit-to-branch
  - id: debug-statements
  - id: check-merge-conflict
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-toml
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable

- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black
    language_version: python3

- repo: https://github.com/adamchainz/blacken-docs
  rev: 1.13.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==23.1.0]

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.256
  hooks:
  - id: ruff
    args: [--fix]

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
  - id: rst-backticks

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.7.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
