name: CI (bleeding edge)
# this workflow is heavily inspired from pandas, see
# https://github.com/pandas-dev/pandas/blob/master/.github/workflows/python-dev.yml

# goals: check stability against
# - dev version of Python, numpy, and matplotlib
# - building with future pip default options

on:
  push:
    branches:
    - main
  pull_request:
    paths:
    - .github/workflows/bleeding-edge.yaml
  schedule:
    # run this every day at 3 am UTC
  - cron: 0 3 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Dev upstream
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python Dev Version
      uses: actions/setup-python@v4
      with:
        python-version: 3.11-dev

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel
        python -m pip install --pre \
          --extra-index https://pypi.anaconda.org/scientific-python-nightly-wheels/simple \
          numpy matplotlib

    - name: Build library
      run: |
        python -m pip install . --no-build-isolation
        python -m pip install --requirement requirements/tests.txt

    - name: Run test suite
      run: |
        pytest --color yes --mpl-results-path=test_results -Werror

    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: test_results
        path: test_results/
