name: CD
on:
  push:
    tags: v*
  pull_request:
    paths:
    - .github/workflows/cd.yml
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: astral-sh/setup-uv@b5f58b2abc5763ade55e4e9d0fe52cd1ff7979ca # v5.2.1
    - name: Build distributions
      run: uv build
    - name: Publish package to PyPI
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
      uses: pypa/gh-action-pypi-publish@67339c736fd9354cd4f8cb0b744f2b82a74b5c70 # v1.12.3
      with:
        user: __token__
        password: ${{ secrets.pypi_token }}
