name: CD
on:
  push:
    tags: v*
  pull_request:
    paths:
    - .github/workflows/cd.yml
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6 # v6.6.1
    - name: Build distributions
      run: uv build
    - name: Publish package to PyPI
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
      uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4
      with:
        user: __token__
        password: ${{ secrets.pypi_token }}
