name: CI
on:
  pull_request:
    paths-ignore:
    - '**/*.md'
  push:
    branches:
    - main
  schedule:
  # run this every Wednesday at 3 am UTC
  - cron: 0 3 * * 3
  workflow_dispatch:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        python-version:
        - '3.10'
        - '3.11'
        - '3.12'
        - '3.13'
        include:
          # only test oldest and most recent Python on other platforms
        - os: macos-latest
          python-version: '3.10'
        - os: macos-latest
          python-version: '3.13'
        - os: windows-latest
          python-version: '3.10'
        - os: windows-latest
          python-version: '3.13'
        - os: ubuntu-20.04
          python-version: '3.10'
          # 2023-09-15 is numpy 1.26.0's release date
          install-args: --resolution=lowest-direct --exclude-newer '2023-09-16'

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Source
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4.2.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run test suite
      shell: bash # for windows compat
      # forcing bytecode compilation for colorspacious
      # see https://github.com/astral-sh/uv/issues/4758
      # Cannot use --frozen here because it overrides options like --resolution
      run: |
        uv run --no-editable --compile-bytecode \
          --group test ${{ matrix.install-args }} \
          pytest --color yes -ra

    - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      if: failure()
      with:
        name: test_results
        path: test_results/

  image-tests:
    name: Image tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4.2.0
      with:
        python-version: '3.13'

    - name: Run Image Tests
      # forcing bytecode compilation for colorspacious
      # see https://github.com/astral-sh/uv/issues/4758
      run: |
        uv run --frozen --no-editable --compile-bytecode --group test \
          pytest --color=yes --mpl -m mpl_image_compare \
                --mpl-generate-summary=html \
                --mpl-results-path=pytest_mpl_results \
                --mpl-baseline-path=tests/baseline

    - name: Generate new image baseline
      if: failure()
      run: |
        uv run --frozen --no-editable --group test \
          pytest --color=yes --mpl -m mpl_image_compare \
                 --mpl-generate-path=pytest_mpl_new_baseline \
                 --last-failed

    # always attempt to upload artifacts, even
    # (and especially) in case of failure.
    - name: Upload pytest-mpl report
      if: always()
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      with:
        name: cmyt_pytest_mpl_results
        path: pytest_mpl_results/*

    - name: Upload pytest-mpl baseline
      if: always()
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      with:
        name: cmyt_pytest_mpl_new_baseline
        path: pytest_mpl_new_baseline/*
        if-no-files-found: ignore

  type-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
        # oldest and newest supported versions
        - '3.10'
        - '3.13'
    concurrency:
      # auto-cancel any in-progress job *on the same branch*
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.python-version }}-typecheck
      cancel-in-progress: true

    steps:
    - name: Checkout repo
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4.2.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run mypy
      run: uv run --frozen --no-editable --group typecheck mypy cmyt
