name: CI
on:
  pull_request:
    paths-ignore:
    - '**/*.md'
  push:
    branches:
    - main
  schedule:
  - cron: 0 3 * * *

jobs:
  tests:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        python-version:
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
        include:
          # only test oldest and most recent Python on other platforms
        - os: macos-latest
          python-version: '3.8'
        - os: macos-latest
          python-version: '3.11'
        - os: windows-latest
          python-version: '3.8'
        - os: windows-latest
          python-version: '3.11'
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build library
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
        python -m pip install --requirement requirements/tests.txt
    - name: Run test suite
      run: |
        python -m pip freeze
        pytest --color yes
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: test_results
        path: test_results/

  minimal-dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Build library
      run: |
        python -m pip install --upgrade pip
        python -m pip install tomli tomli_w
        python scripts/hardpin_minimal_dependencies.py
        python -m pip install .
        python -m pip install --requirement requirements/tests.txt

    - name: Run test suite
      run: |
        python -m pip freeze
        pytest --color yes

  image_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Build library
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
        python -m pip install --requirement requirements/tests.txt

    - name: Run image tests
      run: |
        python -m pip freeze
        pytest --color yes -vvv --mpl --mpl-generate-summary=html --mpl-results-path=mpl_results

    - name: Upload pytest-mpl report
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: image_tests_report
        path: mpl_results/*

  type-check:
    runs-on: ubuntu-latest

    concurrency:
      # auto-cancel any in-progress job *on the same branch*
      group: ${{ github.workflow }}-${{ github.ref }}-typecheck
      cancel-in-progress: true

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        # run with oldest support python version
        # so that we always get compatible versions of
        # core dependencies at type-check time
        python-version: '3.8'

    - name: Build
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
        python -m pip install --requirement requirements/typecheck.txt

    - name: Run mypy
      run: mypy cmyt
